# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HKAdsController' do

pod 'Google-Mobile-Ads-SDK', '~> 7.5.0'
pod 'DomobAdSDK', '~> 4.4.8'
pod 'HKProjectBase', :git => 'https://github.com/Harley-xk/HKProjectBase.git'

end

